/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.NhanVien;
import service.NhanVien_Ser;
import serviceimplement.NhanVien_Imply;

/**
 *
 * @author Quang Ha
 */
public class TrangChu extends javax.swing.JFrame {

    List<NhanVien> listnv;
    private NhanVien_Ser nhanvienser = new NhanVien_Imply();
    private JPanel children;
    private JFrame formcon;

    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        jlbtennhanvien.setText("");
       jpndanhsach.setVisible(true);

    }

    public boolean checkdangnhap() {
        boolean isvalid = true;
        boolean istaikhoan = true;
        boolean ismatkhau = true;
        listnv = nhanvienser.nhanviendangnhap();
        String taikhoan = txttaikhoan.getText();
        if (txttaikhoan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Khong de trong tai khoan");
            isvalid = false;
        }
        String matkhau = new String(txtmatkhau.getPassword());
        if (matkhau.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Khong de trong mat khau");
            isvalid = false;
        }
        if (isvalid == true) {
            for (int i = 0; i < listnv.size(); i++) {
                if (taikhoan.equals(listnv.get(i).getMa()) && matkhau.equals(listnv.get(i).getMatkhau())) {
                    istaikhoan = true;
                    ismatkhau = true;
                    isvalid = true;

                    break;
                } else if (!taikhoan.equals(listnv.get(i).getMa()) || !matkhau.equals(listnv.get(i).getMatkhau())) {
                    istaikhoan = false;

                    isvalid = false;
                } else {
                    istaikhoan = true;
                    isvalid = true;
                }
            }

        }
        if (istaikhoan == false) {
            JOptionPane.showMessageDialog(null, "Sai Tai Khoan Hoac Mat Khau");
        }

        return isvalid;
    }

    private void resetcolor(JPanel jpn) {
        jpn.setBackground(new java.awt.Color(153, 255, 255));
    }

    private void changcolor(JPanel jpn) {
        jpn.setBackground(new java.awt.Color(0, 204, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttaikhoan = new javax.swing.JTextField();
        txtmatkhau = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jlbtennhanvien = new javax.swing.JLabel();
        jpndanhsach = new javax.swing.JPanel();
        jpnbanhang = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jpnnhanvien = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jpnsanpham = new javax.swing.JPanel();
        jblSanPham = new javax.swing.JLabel();
        jpnchitietsp = new javax.swing.JPanel();
        jblChiTietSP = new javax.swing.JLabel();
        jpnkhuyenmai = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpnkhachhang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpnnhaphanphoi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jpndoitra = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jpndoanhthu = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jpnchucvu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpnform = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel4.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Trang Chủ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setOpaque(false);

        jLabel2.setText("Tài Khoản");

        jLabel3.setText("Mật Khẩu");

        jButton1.setText("Đăng Nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Đăng Xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("Nhân Viên:");

        jlbtennhanvien.setText("     ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(25, 49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addComponent(txtmatkhau))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbtennhanvien)))
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtmatkhau, txttaikhoan});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14)
                    .addComponent(jlbtennhanvien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtmatkhau, txttaikhoan});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 597, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 130));

        jpndanhsach.setBackground(new java.awt.Color(153, 255, 255));
        jpndanhsach.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnbanhang.setBackground(new java.awt.Color(153, 255, 255));
        jpnbanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnbanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnbanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnbanhangMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Bán Hàng");

        javax.swing.GroupLayout jpnbanhangLayout = new javax.swing.GroupLayout(jpnbanhang);
        jpnbanhang.setLayout(jpnbanhangLayout);
        jpnbanhangLayout.setHorizontalGroup(
            jpnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnbanhangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnbanhangLayout.setVerticalGroup(
            jpnbanhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnbanhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 60));

        jpnnhanvien.setBackground(new java.awt.Color(153, 255, 255));
        jpnnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnnhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnnhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnnhanvienMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Nhân Viên");

        javax.swing.GroupLayout jpnnhanvienLayout = new javax.swing.GroupLayout(jpnnhanvien);
        jpnnhanvien.setLayout(jpnnhanvienLayout);
        jpnnhanvienLayout.setHorizontalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnnhanvienLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jpnnhanvienLayout.setVerticalGroup(
            jpnnhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 60));

        jpnsanpham.setBackground(new java.awt.Color(153, 255, 255));
        jpnsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnsanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnsanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnsanphamMouseExited(evt);
            }
        });

        jblSanPham.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jblSanPham.setForeground(new java.awt.Color(0, 51, 51));
        jblSanPham.setText("Sản Phẩm");
        jblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnsanphamLayout = new javax.swing.GroupLayout(jpnsanpham);
        jpnsanpham.setLayout(jpnsanphamLayout);
        jpnsanphamLayout.setHorizontalGroup(
            jpnsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsanphamLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jblSanPham)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jpnsanphamLayout.setVerticalGroup(
            jpnsanphamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnsanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 60));

        jpnchitietsp.setBackground(new java.awt.Color(153, 255, 255));
        jpnchitietsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnchitietspMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnchitietspMouseExited(evt);
            }
        });

        jblChiTietSP.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jblChiTietSP.setForeground(new java.awt.Color(0, 51, 51));
        jblChiTietSP.setText("Chi Tiết SP");
        jblChiTietSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblChiTietSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnchitietspLayout = new javax.swing.GroupLayout(jpnchitietsp);
        jpnchitietsp.setLayout(jpnchitietspLayout);
        jpnchitietspLayout.setHorizontalGroup(
            jpnchitietspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnchitietspLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jblChiTietSP)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jpnchitietspLayout.setVerticalGroup(
            jpnchitietspLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblChiTietSP, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnchitietsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 60));

        jpnkhuyenmai.setBackground(new java.awt.Color(153, 255, 255));
        jpnkhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnkhuyenmaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnkhuyenmaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnkhuyenmaiMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 51));
        jLabel9.setText("Khuyến Mãi");

        javax.swing.GroupLayout jpnkhuyenmaiLayout = new javax.swing.GroupLayout(jpnkhuyenmai);
        jpnkhuyenmai.setLayout(jpnkhuyenmaiLayout);
        jpnkhuyenmaiLayout.setHorizontalGroup(
            jpnkhuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhuyenmaiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jpnkhuyenmaiLayout.setVerticalGroup(
            jpnkhuyenmaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnkhuyenmai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 60));

        jpnkhachhang.setBackground(new java.awt.Color(153, 255, 255));
        jpnkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnkhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnkhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnkhachhangMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Khách Hàng");

        javax.swing.GroupLayout jpnkhachhangLayout = new javax.swing.GroupLayout(jpnkhachhang);
        jpnkhachhang.setLayout(jpnkhachhangLayout);
        jpnkhachhangLayout.setHorizontalGroup(
            jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnkhachhangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpnkhachhangLayout.setVerticalGroup(
            jpnkhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 180, -1));

        jpnnhaphanphoi.setBackground(new java.awt.Color(153, 255, 255));
        jpnnhaphanphoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnnhaphanphoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnnhaphanphoiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnnhaphanphoiMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 51));
        jLabel10.setText("Nhà Phân Phối");

        javax.swing.GroupLayout jpnnhaphanphoiLayout = new javax.swing.GroupLayout(jpnnhaphanphoi);
        jpnnhaphanphoi.setLayout(jpnnhaphanphoiLayout);
        jpnnhaphanphoiLayout.setHorizontalGroup(
            jpnnhaphanphoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnnhaphanphoiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jpnnhaphanphoiLayout.setVerticalGroup(
            jpnnhaphanphoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnnhaphanphoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 180, 60));

        jpndoitra.setBackground(new java.awt.Color(153, 255, 255));
        jpndoitra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpndoitraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpndoitraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpndoitraMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Đổi/Trả");

        javax.swing.GroupLayout jpndoitraLayout = new javax.swing.GroupLayout(jpndoitra);
        jpndoitra.setLayout(jpndoitraLayout);
        jpndoitraLayout.setHorizontalGroup(
            jpndoitraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpndoitraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jpndoitraLayout.setVerticalGroup(
            jpndoitraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpndoitra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 180, 60));

        jpndoanhthu.setBackground(new java.awt.Color(153, 255, 255));
        jpndoanhthu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpndoanhthuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpndoanhthuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpndoanhthuMouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 51));
        jLabel12.setText("Doanh Thu");

        javax.swing.GroupLayout jpndoanhthuLayout = new javax.swing.GroupLayout(jpndoanhthu);
        jpndoanhthu.setLayout(jpndoanhthuLayout);
        jpndoanhthuLayout.setHorizontalGroup(
            jpndoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpndoanhthuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jpndoanhthuLayout.setVerticalGroup(
            jpndoanhthuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpndoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 180, 60));

        jpnchucvu.setBackground(new java.awt.Color(153, 255, 255));
        jpnchucvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpnchucvuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpnchucvuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnchucvuMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("Chức Vụ");

        javax.swing.GroupLayout jpnchucvuLayout = new javax.swing.GroupLayout(jpnchucvu);
        jpnchucvu.setLayout(jpnchucvuLayout);
        jpnchucvuLayout.setHorizontalGroup(
            jpnchucvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnchucvuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel13)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jpnchucvuLayout.setVerticalGroup(
            jpnchucvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        jpndanhsach.add(jpnchucvu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 180, -1));

        jPanel2.add(jpndanhsach, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, 750));

        jpnform.setBackground(new java.awt.Color(255, 255, 255));
        jpnform.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jpnform, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 1260, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jlbtennhanvien.getText().length() > 0) {
            JOptionPane.showMessageDialog(null, "Đang Có Tài Khoản Đăng Nhập");
        } else {
            listnv = nhanvienser.nhanviendangnhap();
            if (checkdangnhap()) {
                int chon = JOptionPane.showConfirmDialog(null, "Đăng Nhập", "Hủy", JOptionPane.OK_CANCEL_OPTION);
                if (chon == 0) {
                    for (int i = 0; i < listnv.size(); i++) {
                        if (listnv.get(i).getMa().equals(txttaikhoan.getText())) {
                            jlbtennhanvien.setText(listnv.get(i).getTen());
                        }
                    }
                    jpndanhsach.setVisible(true);
                    txtmatkhau.setText("");
                    txttaikhoan.setText("");
                }

            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jlbtennhanvien.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Chưa Đăng Nhập");
        } else {
            int chon = JOptionPane.showConfirmDialog(null, "Đăng Xuất", "Hủy", JOptionPane.OK_CANCEL_OPTION);
            if (chon == 0) {
                jpndanhsach.setVisible(false);
                jlbtennhanvien.setText("    ");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jpnbanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnbanhangMouseEntered
        changcolor(jpnbanhang);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnbanhangMouseEntered

    private void jpnbanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnbanhangMouseExited
        resetcolor(jpnbanhang);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnbanhangMouseExited

    private void jpnnhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnnhanvienMouseEntered
        changcolor(jpnnhanvien);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnnhanvienMouseEntered

    private void jpnnhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnnhanvienMouseExited
        resetcolor(jpnnhanvien);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnnhanvienMouseExited

    private void jpnsanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnsanphamMouseEntered
        changcolor(jpnsanpham);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnsanphamMouseEntered

    private void jpnsanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnsanphamMouseExited
        resetcolor(jpnsanpham);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnsanphamMouseExited

    private void jpnchitietspMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnchitietspMouseEntered
        changcolor(jpnchitietsp);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnchitietspMouseEntered

    private void jpnchitietspMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnchitietspMouseExited
        resetcolor(jpnchitietsp);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnchitietspMouseExited

    private void jpnkhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnkhachhangMouseEntered
        changcolor(jpnkhachhang);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnkhachhangMouseEntered

    private void jpnkhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnkhachhangMouseExited
        resetcolor(jpnkhachhang);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnkhachhangMouseExited

    private void jpnkhuyenmaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnkhuyenmaiMouseEntered
        changcolor(jpnkhuyenmai);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnkhuyenmaiMouseEntered

    private void jpnkhuyenmaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnkhuyenmaiMouseExited
        resetcolor(jpnkhuyenmai);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnkhuyenmaiMouseExited

    private void jpndoanhthuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpndoanhthuMouseEntered
        changcolor(jpndoanhthu);        // TODO add your handling code here:
    }//GEN-LAST:event_jpndoanhthuMouseEntered

    private void jpndoanhthuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpndoanhthuMouseExited
        resetcolor(jpndoanhthu);        // TODO add your handling code here:
    }//GEN-LAST:event_jpndoanhthuMouseExited

    private void jpndoitraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpndoitraMouseEntered
        changcolor(jpndoitra);        // TODO add your handling code here:
    }//GEN-LAST:event_jpndoitraMouseEntered

    private void jpndoitraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpndoitraMouseExited
        resetcolor(jpndoitra);        // TODO add your handling code here:
    }//GEN-LAST:event_jpndoitraMouseExited

    private void jpnnhaphanphoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnnhaphanphoiMouseEntered
        changcolor(jpnnhaphanphoi);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnnhaphanphoiMouseEntered

    private void jpnnhaphanphoiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnnhaphanphoiMouseExited
        resetcolor(jpnnhaphanphoi);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnnhaphanphoiMouseExited

    private void jpnchucvuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnchucvuMouseEntered
        changcolor(jpnchucvu);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnchucvuMouseEntered

    private void jpnchucvuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnchucvuMouseExited
        resetcolor(jpnchucvu);        // TODO add your handling code here:
    }//GEN-LAST:event_jpnchucvuMouseExited

    private void jpnbanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnbanhangMouseClicked
        children = new BanHang();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jpnbanhangMouseClicked

    private void jpndoitraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpndoitraMouseClicked
        children = new DoiTra();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jpndoitraMouseClicked

    private void jpnchucvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnchucvuMouseClicked
        children = new ChucVu();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();

        // TODO add your handling code here:
    }//GEN-LAST:event_jpnchucvuMouseClicked

    private void jpndoanhthuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpndoanhthuMouseClicked
        children = new DoanhThu();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jpndoanhthuMouseClicked

    private void jpnnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnnhanvienMouseClicked
        children = new view.NhanVien();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jpnnhanvienMouseClicked

    private void jpnkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnkhachhangMouseClicked
        children = new KhachHang();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jpnkhachhangMouseClicked

    private void jpnkhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnkhuyenmaiMouseClicked
        children = new KhuyenMai();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jpnkhuyenmaiMouseClicked

    private void jpnnhaphanphoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnnhaphanphoiMouseClicked
        children = new NhaPhanPhoi();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate();        // TODO add your handling code here:
    }//GEN-LAST:event_jpnnhaphanphoiMouseClicked

    private void jpnsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnsanphamMouseClicked

    }//GEN-LAST:event_jpnsanphamMouseClicked

    private void jblChiTietSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblChiTietSPMouseClicked
          children = new ChiTietSP();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate(); 
    }//GEN-LAST:event_jblChiTietSPMouseClicked

    private void jblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSanPhamMouseClicked
      children = new SanPhamView();
        jpnform.removeAll();
        jpnform.add(children);
        jpnform.validate(); 
    }//GEN-LAST:event_jblSanPhamMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jblChiTietSP;
    private javax.swing.JLabel jblSanPham;
    private javax.swing.JLabel jlbtennhanvien;
    private javax.swing.JPanel jpnbanhang;
    private javax.swing.JPanel jpnchitietsp;
    private javax.swing.JPanel jpnchucvu;
    private javax.swing.JPanel jpndanhsach;
    private javax.swing.JPanel jpndoanhthu;
    private javax.swing.JPanel jpndoitra;
    private javax.swing.JPanel jpnform;
    private javax.swing.JPanel jpnkhachhang;
    private javax.swing.JPanel jpnkhuyenmai;
    private javax.swing.JPanel jpnnhanvien;
    private javax.swing.JPanel jpnnhaphanphoi;
    private javax.swing.JPanel jpnsanpham;
    private javax.swing.JPasswordField txtmatkhau;
    private javax.swing.JTextField txttaikhoan;
    // End of variables declaration//GEN-END:variables
}
